name: demo

on:
 push:
   branches:
     - main
     - master
     - demo

jobs:
 cloning:
   runs-on: self-hosted
   steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: From main branch
       if: ${{ github.ref == 'refs/heads/main' }}
       run: echo "Hello From Main Branch"

     - name: From master branch
       if: ${{ github.ref == 'refs/heads/master' }}
       run: echo "Hello From Master Branch"

     - name: From demo branch
       if: ${{ github.ref == 'refs/heads/demo' }}
       run: echo "Hello From Demo Branch"
