# name: demo
# on: 
#   push: 
#   - main
# jobs:
#   cloning:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#     - name:
#       run: npm install
name: demo
on: 
  push: 
    branches:
      - master
jobs:
  cloning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Node Configure
      uses: bahmutov/npm-install@v1.10.2
    - name: Install dependencies
      run: npm t
      
